- Type: Training
  Trainers: 
    - Name: John John
      Email: john.john@owasp.org
      Image: /assets/images/trainers/no-person.pg
      Twitter: twitter_no_at_symbol
      Biography: >-
          John John has a bio
      TrainerId: trainer001
      #-Name: Trainer Dos
      #Email: tainer.dos@owasp.org
      #Image: /assets/images/trainers/staff_harold.jpg
      #Twitter: Trainer_Dos
      #Biography: The second trainer of this course is a cybersecurity certified professional with more than 25 years of
      #  experience. He works in the field of cybersecurity, cybersecurity research,
      #  and threat intelligence.
      #TrainerId: trainer_dos
  Title: Defend This
  URL: 
  SectionId: sku_IWAHBB
  Description: >-
      Oh yeah, we train defense
